version: "3"

services:
  tor_service:
    build: .
    container_name: express_server
    volumes:
      - "hidden_service:/home/tor/hidden_service"
    ports:
      - "80:80"
    restart: always

volumes:
  hidden_service:
